name: Release Extension

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Compile schemas
        run: glib-compile-schemas schemas/

      - name: Zip extension
        run: |
          zip -r pomodorotimer@anasubaid.dev.shell-extension.zip . \
            -x "./.git/*" "./.github/*" "./.gitignore" \
            -x "./test-logic.js" \
            -x "*.po" "*/.DS_Store"

      - name: Upload to release
        uses: softprops/action-gh-release@v3
        with:
          files: pomodorotimer@anasubaid.dev.shell-extension.zip
          fail_on_unmatched_files: true
          generate_release_notes: true
